### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by d-wasserman** [bzjin/CTPS-DASHBOARD#3]
Hi @bzjin, 

I really thought this project was really interesting, however before I dove in and thought about using parts of your project, I saw there was no license. Can you potentially add a license.txt file to your project with the open source license you want to use? Or do you wish to maintain all copyrights to this work? 

Please see the link below for details. An informal suggestion I have is if you want to open source this project, maybe consider an [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0.txt) license as it has pretty liberal terms of use. 

[License Github](https://help.github.com/articles/licensing-a-repository/)
"You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project. " - From Link. 

Thanks @bzjin 

cc:
@brandonhaydu

**Comment by bzjin** [comment]
Thanks @Holisticnature. Just added an Apache 2.0 license.

**Comment by d-wasserman** [comment]
Hi @bzjin !
Thanks! This will work ! Thank you. 
Just so you know, if you paste the full Apache 2.0 license into a License.txt file, github automatically marks the entire repo as Apache. I found this just a little while ago. 
Ex: [Example Apache 2.0](https://github.com/Holisticnature/FeatureLineSplit/blob/master/License.txt)
It is a minor thing, but something I thought I would mention. 
Thanks again!
